import { theme } from './theme'
import { useAtomValue } from '@effect/atom-react'
import { useKeyboard, useRenderer } from '@opentui/react'
import { useRef, useState, useEffect, memo } from 'react'
import type { TextareaRenderable } from '@opentui/core'
import { Effect } from 'effect'
import { messagesAtom, statusAtom, connectionAtom, samplesAtom } from './state'
import type { makeClient } from './client'
import './chart'
const Conversation=memo(function Conversation(){const messages=useAtomValue(messagesAtom);return <scrollbox flexGrow={1} border borderColor={theme.border} backgroundColor={theme.panel} title='History window (Ctrl+P older)' stickyScroll stickyStart='bottom'><box flexDirection='column'>{messages.map(m=><text key={m.i} fg={m.kind==='user'?theme.user:m.kind==='tool'||m.kind==='echo'?theme.tool:theme.agent}>{m.i+' '+m.kind+' '+m.text.slice(0,4000)+(m.text.length>4000?' [truncated: use zoom]':'')}</text>)}</box></scrollbox>});
function Metrics(){const values=useAtomValue(samplesAtom);const max=Math.max(1,...values);return <box height={5} flexDirection='column'><text fg={theme.text}>Context bytes: peak {max} (relative chart)</text><metricsChart height={3} width={35} samples={values.map(v=>v/max*100)}/></box>}
export function App({client}:{client:ReturnType<typeof makeClient>}){
 const renderer=useRenderer();const editor=useRef<TextareaRenderable>(null);const status=useAtomValue(statusAtom);const connection=useAtomValue(connectionAtom);const [focus,setFocus]=useState(true);const [result,setResult]=useState('');const [selected,setSelected]=useState(0);const pending=useRef(new Set<string>());
 const [composerHeight,setComposerHeight]=useState(1);const resizeComposer=()=>setComposerHeight(Math.min(6,(editor.current?.plainText??'').split('\n').length));
 useEffect(()=>setSelected(v=>Math.max(0,Math.min(v,(status?.nodes.length??1)-1))),[status?.nodes.length]);
 const send=()=>{const text=editor.current?.plainText??'';if(!text.trim()||pending.current.has(text))return;pending.current.add(text);setResult('Awaiting reply; edit a different message to steer');client.run(client.send(text)).then(response=>{setResult('Accepted; original reply continues in history. '+JSON.stringify(response));if(editor.current?.plainText===text){editor.current.clear();resizeComposer()}}).catch(error=>setResult('Failed; draft retained. Outcome may be unknown: '+String(error))).finally(()=>pending.current.delete(text))};
 useKeyboard(key=>{if(key.ctrl&&key.name==='p')client.run(client.older()).catch(e=>setResult(String(e)));if(key.ctrl&&key.name==='q')renderer.destroy();if(key.name==='tab')setFocus(v=>!v);if(key.ctrl&&key.name==='g')send();if(!focus&&key.name==='down')setSelected(v=>Math.max(0,Math.min((status?.nodes.length??1)-1,v+1)));if(!focus&&key.name==='up')setSelected(v=>Math.max(0,v-1));if(!focus&&(key.name==='return'||key.name==='d')){const node=status?.nodes[selected];if(node)client.run(client.inspect(key.name==='d'?{action:'date',id:node.id}:{action:'zoom',id:node.id,n:node.n,page:0})).then(v=>setResult(JSON.stringify(v))).catch(e=>setResult(String(e)))}});
 return <box flexDirection='column' width='100%' height='100%' backgroundColor={theme.background}><text fg={theme.muted} height={1} flexShrink={0}>SLOPCHAT - {connection} - messages {status?.count??0} - summaries {status?.summaryActive??0}</text><Conversation/><box height={8} flexDirection='row'><scrollbox width='50%' border borderColor={theme.border} backgroundColor={theme.panel} title='Memory: Tab / arrows / Enter zoom / D date'><text fg={theme.text}>{status?.nodes.map((n,i)=>(i===selected?'> ':'  ')+n.id+'+'+n.n+'|'+n.text).join('\n')}{status&&status.cursor<status.count?'\nUnsummarized: '+(status.count-status.cursor):''}</text></scrollbox><Metrics/></box><scrollbox height={3}><text fg={result.startsWith('Failed')?theme.error:theme.success}>{result}</text></scrollbox><textarea backgroundColor={theme.element} focusedBackgroundColor={theme.element} textColor={theme.text} focusedTextColor={theme.text} placeholderColor={theme.muted} id='composer' ref={editor} height={composerHeight} flexShrink={0} onContentChange={resizeComposer} focused={focus} wrapMode='word' keyBindings={[{name:'return',action:'submit'},{name:'return',ctrl:true,action:'newline'},{name:'j',ctrl:true,action:'newline'}]} onSubmit={send} placeholder='Enter send / Ctrl+Enter newline'/><text fg={theme.muted} height={1} flexShrink={0}>Enter send - Ctrl+Enter/Ctrl+J newline - Ctrl+G send - Tab focus - Ctrl+Q close</text></box>
}
