import {uiCommands} from './ui-commands'
import {MemoryMap} from './memory-map'
import {makeViewSession,report,type ViewSession} from './view-session'
import { theme } from './theme'
import { useAtomValue } from '@effect/atom-react'
import { useKeyboard, useRenderer } from '@opentui/react'
import { useRef, useState, useEffect, useLayoutEffect, memo } from 'react'
import type { TextareaRenderable } from '@opentui/core'
import { Effect } from 'effect'
import type * as HostAtoms from './state'
import {hostAtoms} from './host-atoms'
import './chart'
import type { makeClient } from './client'

const Conversation=memo(function Conversation({atoms,session}:{atoms:typeof HostAtoms;session:ViewSession}){
 const history=useRef<import('@opentui/core').ScrollBoxRenderable>(null);
 useEffect(()=>{const h=history.current;if(!h)return;session.history=h;const top=session.scrollTop,left=session.scrollLeft;let timer:ReturnType<typeof setInterval>|undefined;let deadline:ReturnType<typeof setTimeout>|undefined;
 const restore=()=>{if(h.isDestroyed)return true;if(h.scrollHeight>h.height){h.scrollTo({x:left,y:top});return true}return false};
 if(top>0&&!restore()){timer=setInterval(()=>{if(restore()&&timer){clearInterval(timer);timer=undefined}},10);deadline=setTimeout(()=>{if(timer)clearInterval(timer)},1000)}
 return()=>{if(timer)clearInterval(timer);if(deadline)clearTimeout(deadline);if(!h.isDestroyed&&h.scrollHeight>h.height){session.scrollTop=h.scrollTop;session.scrollLeft=h.scrollLeft}if(session.history===h)session.history=null}
 },[session]);
 const messages=useAtomValue(atoms.messagesAtom);const latest=useRef(messages.at(-1));const following=useRef(session.scrollTop===0);useLayoutEffect(()=>{const h=history.current;if(!h)return;const previous=latest.current;const last=messages.at(-1);latest.current=last;const changed=!!last&&(!previous||last.i>previous.i||(last.i===previous.i&&last.text!==previous.text));if(changed&&previous&&(last.kind==='user'||following.current)){const bottom=()=>{if(!h.isDestroyed&&h.viewport.height>0){h.scrollTo({x:0,y:h.scrollHeight});session.scrollTop=h.scrollTop;following.current=true}};bottom();const timer=setTimeout(bottom,30);return()=>clearTimeout(timer)}},[messages,session]);useEffect(()=>{const h=history.current;if(!h)return;const timer=setInterval(()=>{if(!h.isDestroyed&&h.viewport.height>0)following.current=h.scrollTop+h.viewport.height>=h.scrollHeight-2},10);return()=>clearInterval(timer)},[session]);return <scrollbox id='history' ref={history} flexGrow={1} border borderColor={theme.border} backgroundColor={theme.panel} title='History window (Ctrl+P older)' stickyScroll={session.scrollTop===0} stickyStart='bottom'><box flexDirection='column'>{messages.map(m=><text key={m.i} fg={m.kind==='user'?theme.user:m.kind==='tool'||m.kind==='echo'?theme.tool:theme.agent}>{m.i+' '+m.kind+' '+m.text.slice(0,4000)+(m.text.length>4000?' [truncated: use zoom]':'')}</text>)}</box></scrollbox>
});
function Metrics({atoms}:{atoms:typeof HostAtoms}){const {samplesAtom}=atoms;const values=useAtomValue(samplesAtom);const max=Math.max(1,...values);return <box height={5} flexDirection='column'><text fg={theme.text}>Context bytes: peak {max} (relative chart)</text><metricsChart colors={theme} height={3} width={35} samples={values.map(v=>v/max*100)}/></box>}
export function App({client,session:provided,atoms=hostAtoms,conference=false}:{client:ReturnType<typeof makeClient>;session?:ViewSession;atoms?:typeof HostAtoms;conference?:boolean}){
 const {statusAtom,connectionAtom}=atoms;
 const localSession=useRef<ViewSession>(provided??makeViewSession());const session=localSession.current;
 const renderer=useRenderer();const editor=useRef<TextareaRenderable>(null);const status=useAtomValue(statusAtom);const connection=useAtomValue(connectionAtom);const [focus,setFocus]=useState(session.focus);const [result,setResult]=useState(session.result);const [selected,setSelected]=useState(session.selected);const pending=useRef(session.pending);const [map,setMap]=useState(false);const [party,setParty]=useState(conference);
 session.focus=focus;session.selected=selected;
 useEffect(()=>session.subscribe(()=>setResult(session.result)),[session]);
 useLayoutEffect(()=>{const e=editor.current;if(e){const cursor=session.cursor;const selection=session.selection;session.editor=e;e.setText(session.draft);e.cursorOffset=cursor;if(selection)e.setSelection(selection.start,selection.end)}return()=>{const e=editor.current??session.editor;if(e&&!e.isDestroyed){session.draft=e.plainText;session.cursor=e.cursorOffset;session.selection=e.getSelection()}session.editor=null}},[]);
 const [composerHeight,setComposerHeight]=useState(Math.min(6,session.draft.split('\n').length));const resizeComposer=()=>{session.draft=editor.current?.plainText??session.draft;setComposerHeight(Math.min(6,(editor.current?.plainText??'').split('\n').length));};
 useEffect(()=>setSelected(v=>Math.max(0,Math.min(v,(status?.nodes.length??1)-1))),[status?.nodes.length]);
 const [completion,setCompletion]=useState('');const commands:string[]=[uiCommands.map,uiCommands.chat];
 const send=()=>{const text=editor.current?.plainText??'';if(!text.trim()||pending.current.has(text))return;const command=text.trim();if(commands.includes(command)){setMap(command===uiCommands.map);editor.current?.clear();resizeComposer();setCompletion('');return}if(command.startsWith('/')&&commands.some(c=>c.startsWith(command))){setCompletion(commands.filter(c=>c.startsWith(command)).join('  '));return}pending.current.add(text);report(session,'Awaiting acceptance; edit a different message to steer');client.run(client.send(text)).then(response=>{report(session,'Accepted; original reply continues in history. '+JSON.stringify(response));const current=session.editor;if(current?.plainText===text){current.clear();session.draft='';resizeComposer()}else if(!current&&session.draft===text){session.draft='';session.cursor=0;session.selection=null}}).catch(error=>report(session,'Failed; draft retained. Outcome may be unknown: '+String(error))).finally(()=>pending.current.delete(text))};
 useKeyboard(key=>{if(party){if(key.name==='escape')setParty(false);return}if(key.ctrl&&key.name==='o')setMap(v=>!v);if(key.ctrl&&key.name==='p')client.run(client.older()).catch(e=>report(session,String(e)));if(key.ctrl&&key.name==='q')renderer.destroy();if(key.name==='tab'){const text=editor.current?.plainText??'';const matches=commands.filter(c=>text.startsWith('/')&&c.startsWith(text));if(focus&&matches.length===1){editor.current?.setText(matches[0]!);resizeComposer();setCompletion(matches[0]!)}else setFocus(v=>!v);}if(key.ctrl&&key.name==='g')send();if(!focus&&key.name==='down')setSelected(v=>Math.max(0,Math.min((status?.nodes.length??1)-1,v+1)));if(!focus&&key.name==='up')setSelected(v=>Math.max(0,v-1));if(!focus&&(key.name==='return'||key.name==='d')){const node=status?.nodes[selected];if(node)client.run(client.inspect(key.name==='d'?{action:'date',id:node.id}:{action:'zoom',id:node.id,n:node.n,page:0})).then(v=>report(session,JSON.stringify(v))).catch(e=>report(session,String(e)))}});
 return <box flexDirection='column' width='100%' height='100%' backgroundColor={theme.background}><text fg={theme.muted} height={1} flexShrink={0}>SLOPCHAT - {connection} - messages {status?.count??0} - summaries {status?.summaryActive??0}</text>{map?<MemoryMap status={status} selected={selected}/>:<Conversation atoms={atoms} session={session}/>}<box height={8} flexDirection='row'><scrollbox width='50%' border borderColor={theme.border} backgroundColor={theme.panel} title='Memory: Tab / arrows / Enter zoom / D date'><text fg={theme.text}>{status?.nodes.map((n,i)=>(i===selected?'> ':'  ')+n.id+'+'+n.n+'|'+n.text).join('\n')}{status&&status.cursor<status.count?'\nUnsummarized: '+(status.count-status.cursor):''}</text></scrollbox><Metrics atoms={atoms}/></box><scrollbox height={3}><text fg={result.startsWith('Failed')?theme.error:theme.success}>{result}</text></scrollbox><textarea backgroundColor={theme.element} focusedBackgroundColor={theme.element} textColor={theme.text} focusedTextColor={theme.text} placeholderColor={theme.muted} id='composer' ref={editor} onCursorChange={()=>{const e=editor.current;if(e){session.cursor=e.cursorOffset;session.selection=e.getSelection()}}} height={composerHeight} flexShrink={0} onContentChange={()=>{resizeComposer();const text=editor.current?.plainText??'';setCompletion(text.startsWith('/')?commands.filter(c=>c.startsWith(text)).join('  '):'')}} focused={focus&&!party} wrapMode='word' keyBindings={[{name:'return',action:'submit'},{name:'return',ctrl:true,action:'newline'},{name:'j',ctrl:true,action:'newline'}]} onSubmit={send} placeholder='Enter send / Ctrl+Enter newline'/>{completion?<text fg={theme.tool}>Commands: {completion} - Tab complete / Enter execute</text>:null}<text fg={theme.muted} height={1} flexShrink={0}>Enter send - Ctrl+Enter/Ctrl+J newline - Ctrl+G send - Tab focus - {uiCommands.map} {uiCommands.chat} - Tab complete - Ctrl+O map - Ctrl+Q close</text>{party?<box id='conference-modal' position='absolute' left='5%' top='15%' width='90%' height={16} border borderStyle='double' borderColor='#ff55dd' backgroundColor='#180a2e' flexDirection='column' alignItems='center' justifyContent='center'><text fg='#55ffff'>{String.fromCodePoint(10022,32,9670,32,10022,32,9670,32,10022)}</text><text fg='#ff55dd'>CONFERENCE // LIVE // LEVEL UP</text><text fg='#ffffff'> </text><text fg='#ffff55'>{'★ ПРИВЕТ КОНФА ★'}</text><text fg='#ffffff'> </text><text fg='#55ffff'>{'ВЫ В ЭФИРЕ'}</text><text fg='#ff88ee'>NEON. CODE. PURE TERMINAL MAGIC.</text><text fg='#ffff55'>* &lt;&gt; * &lt;&gt; * &lt;&gt; * &lt;&gt; *</text><text fg='#bbaadd'>Esc - back to chat</text></box>:null}</box>
}
