import {useState,useEffect,useRef} from 'react'
import type {ScrollBoxRenderable} from '@opentui/core'
import {useKeyboard} from '@opentui/react'
import {Effect,Schema} from 'effect'
import {theme} from './theme'
import type {Status} from './protocol'
import type {makeClient} from './client'
const Child=Schema.Struct({l:Schema.Number,i:Schema.Number,text:Schema.String})
const Original=Schema.Struct({id:Schema.Number,kind:Schema.String,text:Schema.String,page:Schema.Number,pages:Schema.Number,date:Schema.String})
const Reply=Schema.Struct({value:Schema.Union([Schema.Array(Child),Original])})
type Block={id:number;n:number;text:string}
export function MemoryMap({status,selected,client,active,onFocus,onExit,enabled}:{status:Status|null|undefined;selected:number;client:ReturnType<typeof makeClient>;active:boolean;onFocus:()=>void;onExit:()=>void;enabled:boolean}){
 const [levels,setLevels]=useState<{blocks:Block[];index:number}[]>([]);const [original,setOriginal]=useState<Schema.Schema.Type<typeof Original>|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const scroll=useRef<ScrollBoxRenderable>(null);
 const level=levels.at(-1);const blocks=level?.blocks??status?.nodes??[];const choice=level?.index??selected;const node=blocks[choice];
 useEffect(()=>{let attempts=0;const timer=setInterval(()=>{const box=scroll.current;const child=box?.content.findDescendantById('memory-block-'+choice);if(box&&child&&box.viewport.height>0){const top=box.viewport.y;const bottom=top+box.viewport.height;if(child.y<top||child.y+child.height>bottom){const delta=child.height>=box.viewport.height||child.y<top?child.y-top:child.y+child.height-bottom;box.scrollTo(box.scrollTop+delta);box.content.translateY=-box.scrollTop;box.requestRender()}}if(++attempts>=50)clearInterval(timer)},10);return()=>clearInterval(timer)},[choice,level,status?.nodes]);
 const open=(page=0)=>{if(!node||busy)return;setBusy(true);setError('');client.run(client.inspect({action:'zoom',id:node.id,n:node.n,page}).pipe(Effect.flatMap(Schema.decodeUnknownEffect(Reply)))).then(r=>{const value=r.value;if('id' in value)setOriginal(value);else {setLevels(v=>[...v,{blocks:value.map(n=>({id:n.i*2**n.l,n:2**n.l,text:n.text})),index:0}]);setOriginal(null)}}).catch(e=>setError(String(e))).finally(()=>setBusy(false))};
 useKeyboard(k=>{if(k.name==='escape'&&enabled){k.preventDefault();if(original)setOriginal(null);else if(level)setLevels(v=>v.slice(0,-1));else onExit();return}if(!active)return;if(k.name==='return'){k.preventDefault();open()}if(level&&(k.name==='up'||k.name==='down')){k.preventDefault();setOriginal(null);setLevels(v=>v.map((l,i)=>i===v.length-1?{...l,index:l.blocks.length?(l.index+(k.name==='up'?-1:1)+l.blocks.length)%l.blocks.length:0}:l))}if(original&&(k.name==='left'||k.name==='right')){k.preventDefault();open(Math.max(0,Math.min(original.pages-1,original.page+(k.name==='left'?-1:1))))}});
 return <scrollbox contentOptions={{flexDirection:'column'}} height={0} minHeight={0} ref={scroll} id='memory-map' onMouseDown={onFocus} flexGrow={1} border borderColor={theme.agent} backgroundColor={theme.panel} title='Agent memory context / archive explorer'><text fg={theme.muted}>Chat is memory. Blocks cover message ranges, not topics.</text><text fg={theme.tool}>{level?'Expanded archive: depth '+levels.length:'Agent context: '+(status?.viewTotal??0)+' blocks; showing '+blocks.length+' at offset '+(status?.offset??0)}</text><text fg={theme.muted}>{status&&status.cursor<status.count?'Unsummarized: '+(status.count-status.cursor):''}</text><text fg={theme.muted}>Ctrl+F focus / arrows select / Enter expand / Esc parent / chat / left-right pages</text>{blocks.map((n,i)=><text id={'memory-block-'+i} wrapMode='word' width='100%' flexShrink={0} key={n.id+'+'+n.n} fg={i===choice?theme.user:theme.muted}>{(i===choice?'> ':'  ')+(n.n===1?'message ':'summary ')+n.id+'..'+(n.id+n.n-1)+' ('+n.n+') '+n.text}</text>)}<text fg={theme.agent}>{original?'ORIGINAL '+original.id+' / '+original.kind+' / '+original.date+' / page '+(original.page+1)+'/'+original.pages:'SELECTED '+(node?node.id+'+'+node.n:'none')}</text><text wrapMode='word' width='100%' flexShrink={0} fg={theme.text}>{original?.text??(level?node?.text:'')??'Waiting for memory view'}</text>{busy?<text fg={theme.tool}>Loading from Lisp...</text>:null}{error?<text fg={theme.error}>{error}</text>:null}</scrollbox>
}
