;;; boot-test.el --- Ouro bootstrap and adapter boundaries -*- lexical-binding: t -*-
(require 'ert)
(load (expand-file-name "../boot.el" (file-name-directory load-file-name)))
(ert-deftest ouro-bootstrap-one-request-drops-results ()
  (let* ((calls 0) (agent-eval-count 0) seen
        (agent-eval-function (lambda (expression) (setq seen expression) "result"))
        (agent-model-function
         (lambda (_messages)
           (cl-incf calls)
           '(((type . "tool_use") (input . ((expression . "(+ 1 2)"))))))))
    (should (equal (funcall #'agent-bootstrap "task") "result"))
    (should (= calls 1)) (should (= agent-eval-count 1))
    (should (equal seen "(+ 1 2)"))))
(ert-deftest ouro-eval-error-is-data ()
  (let ((agent-eval-function nil))
    (should (string-match-p "Arithmetic error" (agent-eval "(/ 1 0)")))))
(ert-deftest ouro-bootstrap-model-writes-and-invokes-agent ()
  (let* ((calls 0)
        (agent-model-function
         (lambda (_messages)
           (cl-incf calls)
           '(((type . "tool_use")
              (input . ((expression . "(progn (defun agent (task) (concat \"written:\" task)) (agent \"task\"))"))))))))
    (cl-letf (((symbol-function 'agent) (symbol-function 'agent-bootstrap)))
      (should (equal (agent-boot "task") "\"written:task\""))
      (should (equal (agent "next") "written:next"))
      (should (= calls 1)))))
(ert-deftest ouro-transport-defers-eval-without-execution ()
  (let* ((c (slopchat--connection-create :runs (make-hash-table :test 'equal)))
         (run (slopchat--run-create :thread "thread" :deferred t
                                   :handler (lambda (&rest _) (ert-fail "Transport executed tool")))))
    (puthash "thread" run (slopchat-connection-runs c))
    (cl-letf (((symbol-function 'slopchat-codex-send)
               (lambda (&rest _) (ert-fail "Transport returned a tool result"))))
      (slopchat-codex--dispatch
       c '(:id "request" :method "item/tool/call"
           :params (:threadId "thread" :callId "call" :tool "eval"
                     :arguments (:expression "(+ 1 2)"))))
      (should (= (length (slopchat-run-requests run)) 1)))))
(ert-deftest ouro-model-response-cancels-and-returns-tool-data ()
  (let* ((connection (slopchat--connection-create :runs (make-hash-table :test 'equal)))
         (run (slopchat--run-create :connection connection :thread "fresh" :turn "turn"))
         interrupted forgotten)
    (cl-letf (((symbol-function 'slopchat-codex-thread) (lambda (&rest _) "fresh"))
              ((symbol-function 'slopchat-codex-run) (lambda (&rest _) run))
              ((symbol-function 'slopchat-codex-pump)
               (lambda (&rest _)
                 (should (slopchat-run-deferred run))
                 (setf (slopchat-run-requests run)
                       '((:id 91 :params (:callId "call" :tool "eval"
                                          :arguments (:expression "(+ 19 23)")))))))
              ((symbol-function 'slopchat-codex-rpc)
               (lambda (_ method params)
                 (setq interrupted (list method params))))
              ((symbol-function 'slopchat-codex-forget-thread)
               (lambda (_ thread) (setq forgotten thread))))
      (let ((blocks (slopchat-model-response connection "/tmp" "instructions" [] nil)))
        (should (equal (alist-get 'type (car blocks)) "tool_use"))
        (should (equal (alist-get 'expression (alist-get 'input (car blocks))) "(+ 19 23)"))
        (should (equal (car interrupted) "turn/interrupt"))
        (should (slopchat-run-done run)) (should (equal forgotten "fresh"))))))
