;;; slopchat-test.el --- Durable memory and protocol tests -*- lexical-binding: t -*-
(require 'ert)
(add-to-list 'load-path (expand-file-name "../lisp" (file-name-directory load-file-name)))
(require 'slopchat)

(defmacro slopchat-with-chat (&rest body)
  `(let* ((directory (make-temp-file "slopchat-test-" t))
          (chat (slopchat-open directory)))
     (unwind-protect (progn ,@body)
       (slopchat-close chat) (delete-directory directory t))))
(defun slopchat-test-text (file)
  (with-temp-buffer (insert-file-contents file) (buffer-string)))

(ert-deftest slopchat-utf8-lossless-splitting ()
  (dolist (limit '(4 5 7 20 512))
    (dolist (text '("" "hello" "привет" "🙂a🦀ё\n𐀀終"))
      (let ((parts (slopchat-split text limit)))
        (should (equal (apply #'concat parts) text))
        (dolist (part parts) (should (<= (slopchat-bytes part) limit))))))
  (should (= (slopchat-bytes "🙂ё") 6)))
(ert-deftest slopchat-tool-output-head-tail ()
  (let ((text (concat (make-string 16000 ?a) (make-string 16000 ?b))))
    (should (equal (slopchat-clip text) (concat (make-string 15000 ?a) (make-string 15000 ?b))))))
(ert-deftest slopchat-no-model-for-short-source ()
  (slopchat-with-chat
   (slopchat-log chat "user" "one") (slopchat-log chat "user" "two")
   (should (slopchat-node chat '(1 0)))
   (should-not (slopchat-queue-head (slopchat-chat-jobs chat)))
   (should (= (slopchat-chat-cursor chat) 2))))
(ert-deftest slopchat-node-once-and-reopen-identical ()
  (slopchat-with-chat
   (slopchat-log chat "user" "first") (slopchat-log chat "slopchat" "second")
   (let* ((view (slopchat-render chat))
          (checkpoint (slopchat-test-text (expand-file-name "view.json" directory)))
          (tree (car (directory-files (expand-file-name "tree" directory) t "jsonl$")))
          (before (slopchat-test-text tree)))
     (slopchat-build chat '(0 0) "replacement")
     (should (equal (slopchat-test-text tree) before))
     (slopchat-close chat) (setq chat (slopchat-open directory))
     (should (equal (slopchat-render chat) view))
     (should (equal (slopchat-test-text (expand-file-name "view.json" directory)) checkpoint))
     (should (equal (plist-get (slopchat-zoom chat 0 1) :text) "first")))))
(ert-deftest slopchat-lock-exclusion-and-release ()
  (slopchat-with-chat
   (should-error (slopchat-open directory))
   (slopchat-close chat) (setq chat (slopchat-open directory))
   (should-not (slopchat-chat-closed chat))))
(ert-deftest slopchat-log-splitting-and-pagination ()
  (let ((slopchat-message-bytes 8) (slopchat-page-bytes 4))
    (slopchat-with-chat
     (let* ((text "🙂привет🙂") (ids (slopchat-log chat "note" text)))
       (should (equal (mapconcat (lambda (id) (plist-get (gethash id (slopchat-chat-messages chat)) :text)) ids "") text))
       (let ((first (slopchat-zoom chat 0 1)))
         (should (> (plist-get first :pages) 1))
         (should (<= (slopchat-bytes (plist-get first :text)) 4)))))))
(ert-deftest slopchat-zoom-date-validation ()
  (slopchat-with-chat
   (dotimes (_ 4) (slopchat-log chat "user" "x"))
   (should (= (length (slopchat-zoom chat 0 4)) 2))
   (should (string-match-p "Z$" (slopchat-date chat 0)))
   (dolist (range '((1 2) (0 3) (-1 1) (0 0) (0 8)))
     (should-error (slopchat-zoom chat (car range) (cadr range))))
   (should-error (slopchat-zoom chat 0 1 99)) (should-error (slopchat-date chat 99))))
(ert-deftest slopchat-empty-prefix-is-empty ()
  (slopchat-with-chat
   (slopchat-log chat "user" "do not leak")
   (should (equal (slopchat-render chat nil) "<chat>\n</chat>"))
   (should (equal (slopchat--context chat '(0 0)) "<chat>\n</chat>"))))
(ert-deftest slopchat-t10-merge-regression ()
  (let* ((view '((2 0) (2 1) (0 8) (0 9)))
         (best (slopchat-best-merge view 10)))
    (should (equal (car best) '(0 8)))))
(defun slopchat-test-push (state states)
  (if (null states) (list 0 state nil)
    (if (= (car states) 0) (list 1 (cadr states) (caddr states))
      (list 0 state (slopchat-test-push (cadr states) (caddr states))))))
(ert-deftest slopchat-rollback-order-20001-steps ()
  (let (states view)
    (dotimes (time 20001)
      (setq states (slopchat-test-push time states) view (nconc view (list (list 0 time))))
      (let ((s states) starts)
        (while s (push (cadr s) starts) (setq s (caddr s)))
        (while (> (length view) (length starts))
          (let* ((cell (slopchat-best-merge view (1+ time))) (key (car cell)))
            (should cell)
            (setcar cell (list (1+ (car key)) (/ (cadr key) 2)))
            (setcdr cell (cddr cell))))
        (should (equal (mapcar (lambda (key) (car (slopchat-range key))) view) starts))))))
(ert-deftest slopchat-delayed-leaves-publish-contiguous-prefix ()
  (slopchat-with-chat
   (slopchat-log chat "user" (make-string 600 ?a))
   (slopchat-log chat "user" "later")
   (should (= (slopchat-chat-cursor chat) 0))
   (should (equal (slopchat-render chat) "<chat>\n</chat>"))
   (slopchat-build chat '(0 0) "user: earlier")
   (should (= (slopchat-chat-cursor chat) 2))))
(ert-deftest slopchat-summary-retries-keep-shortest ()
  (slopchat-with-chat
   (let* ((attempts 0) prompts
         (slopchat-summary-function
          (lambda (_chat _key prompt _context done)
            (push prompt prompts)
            (cl-incf attempts)
            (funcall done (make-string (+ 520 (- 6 attempts)) ?x) nil))))
     (slopchat-log chat "user" (make-string 600 ?a))
     (slopchat-schedule chat)
     (should (= attempts 5))
     (should (string-prefix-p "Too long:" (car prompts)))
     (should (= (plist-get (slopchat-node chat '(0 0)) :size) 521))
     (should (= (slopchat-chat-active chat) 0)))))
(ert-deftest slopchat-summary-failure-retry-on-next-message ()
  (slopchat-with-chat
   (let ((slopchat-summary-function (lambda (_c _k _p _v done) (funcall done nil "offline"))))
     (slopchat-log chat "user" (make-string 600 ?a)) (slopchat-schedule chat)
     (should (equal (slopchat-chat-failed chat) '((0 0))))
     (slopchat-log chat "user" "next")
     (let ((slopchat-summary-function (lambda (_c _k _p _v done) (funcall done "summary" nil))))
       (slopchat-schedule chat)
       (should-not (slopchat-chat-failed chat))
       (should (= (slopchat-chat-cursor chat) 2))))))
(ert-deftest slopchat-summary-scheduling-is-bounded ()
  (slopchat-with-chat
   (let* (callbacks (slopchat-summary-function
                    (lambda (_chat key _prompt _context done) (push (cons key done) callbacks))))
     (dotimes (_ 20) (slopchat-log chat "user" (make-string 600 ?a)))
     (slopchat-schedule chat)
     (should (= (slopchat-chat-active chat) 8))
     (should (= (length callbacks) 8))
     (should (= (slopchat-chat-leaf-slots chat) 8))
     (let ((entry (pop callbacks))) (funcall (cdr entry) "built out of order" nil))
     (should (= (slopchat-chat-cursor chat) 0))
     (slopchat-schedule chat)
     (should (= (slopchat-chat-active chat) 8)))))
(ert-deftest slopchat-checkpoint-recovers-only-committed-tail ()
  (slopchat-with-chat
   (slopchat-log chat "user" "old")
   (let ((checkpoint (slopchat-test-text (expand-file-name "view.json" directory))))
     (slopchat-log chat "slopchat" "tail")
     ;; Simulate log/tree committed, checkpoint rename not yet performed.
     (slopchat--write (expand-file-name "view.json" directory) checkpoint)
     (slopchat-close chat) (setq chat (slopchat-open directory))
     (should (= (slopchat-chat-cursor chat) 2))
     (should (equal (car (slopchat-chat-view chat)) '(0 0)))
     (should (equal (plist-get (slopchat-zoom chat 1 1) :text) "tail")))))
(ert-deftest slopchat-incomplete-record-tail-is-salvaged ()
  (slopchat-with-chat
   (slopchat-log chat "user" "old")
   (let ((file (car (directory-files (expand-file-name "main" directory) t "jsonl$"))))
     (slopchat--write file "{\"i\":1" t)
     (slopchat-close chat)
     (setq chat (slopchat-open directory))
     (should (= (slopchat-chat-count chat) 1))
     (should (string-suffix-p "\n" (slopchat-test-text file)))
     (should (= (length (directory-files (file-name-directory file) nil "incomplete-")) 1)))))
(ert-deftest slopchat-turns-have-only-view-continuity ()
  (slopchat-with-chat
   (let* (prompts (slopchat-turn-function
                  (lambda (_chat prompt done) (push prompt prompts) (funcall done "ok" nil))))
     (should (equal (slopchat-send chat "first") "ok"))
     (should (equal (slopchat-send chat "second") "ok"))
     (should (equal (cadr prompts) "<chat>\n</chat>\n\nfirst"))
     (should (string-match-p (regexp-quote "0+1|user: first") (car prompts)))
     (should-not (string-match-p "user: second" (car prompts))))))
(ert-deftest slopchat-transport-preserves-out-of-order-rpc ()
  (let ((c (slopchat--connection-create :responses (make-hash-table :test 'equal)
                                        :runs (make-hash-table :test 'equal))))
    (slopchat-codex--dispatch c '(:id 2 :result (:v "second")))
    (slopchat-codex--dispatch c '(:id 1 :result (:v "first")))
    (should (equal (plist-get (plist-get (gethash 2 (slopchat-connection-responses c)) :result) :v) "second"))))
(ert-deftest slopchat-transport-routes-two-runs-and-drops-thoughts ()
  (let* ((c (slopchat--connection-create :responses (make-hash-table :test 'equal)
                                         :runs (make-hash-table :test 'equal)))
         (a (slopchat--run-create :connection c :thread "a"))
         (b (slopchat--run-create :connection c :thread "b")))
    (puthash "a" a (slopchat-connection-runs c)) (puthash "b" b (slopchat-connection-runs c))
    (slopchat-codex--dispatch c '(:method "item/completed" :params (:threadId "b" :item (:type "agentMessage" :text "B"))))
    (slopchat-codex--dispatch c '(:method "item/completed" :params (:threadId "a" :item (:type "reasoning" :text "secret"))))
    (should (equal (slopchat-codex-result b) "B")) (should (equal (slopchat-codex-result a) ""))))
(ert-deftest slopchat-compaction-tools-denied ()
  (let* ((c (slopchat--connection-create :responses (make-hash-table :test 'equal)
                                         :runs (make-hash-table :test 'equal)))
         (run (slopchat--run-create :connection c :thread "summary"
                                   :handler (lambda (_tool _args) (error "Compaction calls cannot execute tools")))) sent)
    (puthash "summary" run (slopchat-connection-runs c))
    (cl-letf (((symbol-function 'slopchat-codex-send) (lambda (_c message) (setq sent message))))
      (slopchat-codex--dispatch c '(:id 7 :method "item/tool/call" :params (:threadId "summary" :tool "emacs_eval" :arguments (:expression "(error)"))))
      (should (eq (plist-get (plist-get sent :result) :success) :false)))))

(ert-deftest slopchat-sawtooth-batches-and-compaction-context ()
  (slopchat-with-chat
   (let* ((drops 0) (peak 0) (previous 0)
          (slopchat-summary-function
           (lambda (_chat key _prompt context done)
             (should (<= (slopchat-bytes context) slopchat-compaction-high))
             (funcall done (concat (format "node %S: " key) (make-string 435 ?x)) nil))))
     ;; Durability has separate real-file tests. This simulation tests memory and
     ;; scheduler behavior without hundreds of disk syncs or subscription calls.
     (cl-letf (((symbol-function 'slopchat--write) #'ignore)
               ((symbol-function 'slopchat-checkpoint) #'ignore))
       (dotimes (i 700)
         (slopchat-log chat "user" (concat (number-to-string i) (make-string 600 ?a)))
         (slopchat-schedule chat)
         (let ((size (slopchat-view-size chat (slopchat-chat-view chat))))
           (setq peak (max peak size))
           (when (< size previous)
             (cl-incf drops) (should (<= size slopchat-view-low)))
           (setq previous size))
         (slopchat--validate-view chat (slopchat-chat-view chat) (1+ i))
         (slopchat--validate-view chat (slopchat-chat-comp-view chat) (1+ i)))
       (should (>= drops 3))
       (should (> peak 120000))
       (should (<= previous slopchat-view-high))))))
(ert-deftest slopchat-delayed-parent-keeps-pending-batch ()
  (let ((slopchat-view-high 150) (slopchat-view-low 90)
        (slopchat-compaction-high 150) (slopchat-compaction-low 90))
    (slopchat-with-chat
     (dotimes (_ 2) (slopchat-log chat "user" (make-string 600 ?a)))
     (slopchat-build chat '(0 0) (make-string 75 ?x))
     (slopchat-build chat '(0 1) (make-string 75 ?y))
     ;; Joined short sources created the parent automatically: use a test stub
     ;; to model a delayed parent, then restore it and finish the pending batch.
     (let ((parent (slopchat-node chat '(1 0))))
       (remhash '(1 0) (slopchat-chat-nodes chat))
       (setf (slopchat-chat-view chat) '((0 0) (0 1))
             (slopchat-chat-comp-view chat) '((0 0) (0 1))
             (slopchat-chat-batching chat) t)
       (slopchat--shrink chat)
       (should (slopchat-chat-batching chat))
       (puthash '(1 0) (plist-put parent :text "short merged summary") (slopchat-chat-nodes chat))
       (slopchat--shrink chat)
       (should-not (slopchat-chat-batching chat))
       (should (equal (slopchat-chat-view chat) '((1 0))))))))
(ert-deftest slopchat-new-thread-per-model-response ()
  (slopchat-with-chat
   (let ((threads 0))
     ;; Already bootstrapped agent: one model request per invocation here.
     (setf (slopchat-chat-agent chat)
           (lambda (prompt) (alist-get 'text (car (agent-prompt `[(:role "user" :content ,prompt)])))))
     (cl-letf (((symbol-function 'slopchat--connection) (lambda (_chat) 'connection))
               ((symbol-function 'slopchat-model-response)
                (lambda (&rest _args)
                  (cl-incf threads) '(((type . "text") (text . "ok"))))))
       (should (equal (slopchat-send chat "one") "ok"))
       (should (equal (slopchat-send chat "two") "ok"))
       (should (= threads 2))))))
(ert-deftest slopchat-kernel-lock-survives-no-stale-owner ()
  (slopchat-with-chat
   (delete-process (slopchat-chat-lock chat))
   (accept-process-output nil 0.05)
   (let ((reopened (slopchat-open directory)))
     (unwind-protect (should reopened) (slopchat-close reopened)))))
(ert-deftest slopchat-async-response-has-one-consumer ()
  (let* ((c (slopchat--connection-create :responses (make-hash-table :test 'equal)
                                         :runs (make-hash-table :test 'equal)))
         received)
    (puthash 17 (lambda (response) (setq received response)) (slopchat-connection-callbacks c))
    (slopchat-codex--dispatch c '(:id 17 :result (:ok t)))
    (should (plist-get (plist-get received :result) :ok))
    (should-not (gethash 17 (slopchat-connection-callbacks c)))
    (should-not (gethash 17 (slopchat-connection-responses c)))))
(ert-deftest slopchat-early-clarification-waits-for-turn-id ()
  (slopchat-with-chat
   (let ((run (slopchat--run-create :thread "active")) result seen)
     (setf (slopchat-chat-run chat) run)
     (slopchat-submit chat "correction" (lambda (_text error) (setq result error)))
     (should-not result)
     (should (= (slopchat-chat-count chat) 1))
     (setf (slopchat-run-turn run) "turn-id")
     (cl-letf (((symbol-function 'slopchat-codex-steer)
                (lambda (_run text) (setq seen text))))
       (slopchat-pump chat)
       (should (equal seen "correction")) (should (eq result 'steered))
       (should-not (slopchat-queue-head (slopchat-chat-queued-input chat)))
       (should (= (slopchat-chat-count chat) 1))))))
(ert-deftest slopchat-steer-race-queues-without-duplicate ()
  (slopchat-with-chat
   (let* ((run (slopchat--run-create :thread "active" :turn "turn-id")) result
          (slopchat-turn-function (lambda (_chat _prompt done) (funcall done "fresh reply" nil))))
     (setf (slopchat-chat-run chat) run)
     (cl-letf (((symbol-function 'slopchat-codex-steer)
                (lambda (&rest _args)
                  (setf (slopchat-chat-run chat) nil)
                  (error "Turn already completed"))))
       (slopchat-submit chat "correction" (lambda (text _error) (setq result text)))
       (should (equal result "fresh reply"))
       (should (= (slopchat-chat-count chat) 2))
       (should (equal (plist-get (gethash 0 (slopchat-chat-messages chat)) :kind) "user"))
       (should (equal (plist-get (gethash 1 (slopchat-chat-messages chat)) :kind) "slopchat"))))))
(ert-deftest slopchat-async-input-reports-summary-failure ()
  (slopchat-with-chat
   (let* (reported
          (slopchat-summary-function (lambda (_chat _key _prompt _view done) (funcall done nil "offline"))))
     (slopchat-log chat "user" (make-string 600 ?a))
     (slopchat-schedule chat)
     (slopchat-submit chat "next" (lambda (_text error) (setq reported error)))
     (should (string-match-p "Prior summaries failed" reported))
     (should (= (slopchat-chat-count chat) 3))
     (should (equal (plist-get (gethash 2 (slopchat-chat-messages chat)) :kind) "work"))
     (should-not (slopchat-queue-head (slopchat-chat-queued-input chat))))))
(ert-deftest slopchat-ouro-bootstrap-loop-and-next-turn ()
  (slopchat-with-chat
   (let* ((calls 0) histories
          (slopchat-summary-function
           (lambda (_chat _key _prompt _context done) (funcall done "summary" nil)))
          ;; This code comes from the fake model response, not the runtime.
          (written
           "(progn (defun agent (prompt) (let ((history (vector (list :role \"user\" :content prompt))) blocks results done text) (while (not done) (setq blocks (agent-prompt history) results nil) (dolist (block blocks) (if (equal (alist-get 'type block) \"tool_use\") (push (list :type \"tool_result\" :tool_use_id (alist-get 'id block) :content (agent-eval (alist-get 'expression (alist-get 'input block)))) results) (setq text (alist-get 'text block)))) (if results (setq history (vconcat history (vector (list :role \"assistant\" :content blocks) (list :role \"user\" :content (vconcat results))))) (setq done t))) text)) (agent \"first\"))"))
     (cl-letf (((symbol-function 'slopchat--connection) (lambda (_chat) 'fake))
               ((symbol-function 'slopchat-model-response)
                (lambda (_c _d _i messages &rest _)
                  (push messages histories)
                  (pcase (cl-incf calls)
                    (1 `(((type . "tool_use") (input . ((expression . ,written))))))
                    (2 '(((type . "tool_use") (id . "eval-42")
                          (input . ((expression . "(+ 19 23)"))))))
                    (_ '(((type . "text") (text . "42"))))))))
       (should (equal (slopchat-send chat "first") "42"))
       (should (functionp (slopchat-chat-agent chat)))
       (should (string-match-p "tool_result" (prin1-to-string (car histories))))
       (should (equal (slopchat-send chat "second") "42"))
       (should (= calls 4))
       (should-not (string-match-p "tool_result" (prin1-to-string (car histories))))))))
(ert-deftest slopchat-ouro-bootstrap-failure-reported ()
  (slopchat-with-chat
   (cl-letf (((symbol-function 'slopchat--connection) (lambda (_chat) 'fake))
             ((symbol-function 'slopchat-model-response)
              (lambda (&rest _) '(((type . "tool_use") (input . ((expression . "("))))))))
     (should-error (slopchat-send chat "task"))
     (should-not (slopchat-chat-agent chat))
     (should-not (slopchat-chat-run chat)))))
