;;; -*- lexical-binding: t -*-
(require 'ert)
(require 'cl-lib)
(require 'slopchat-cli)
(ert-deftest slopchat-opt-in-acceptance ()
 (let (responses callback)
  (cl-letf (((symbol-function 'slopchat-cli--reply) (lambda (_ value) (push value responses)))
            ((symbol-function 'slopchat-submit) (lambda (_ _text cb &optional accepted _queue-only) (setq callback cb) (when accepted (funcall accepted 42)) 42)))
   (slopchat-cli--request nil nil "{\"action\":\"send\",\"text\":\"hello\",\"ack\":true}")
   (should (equal responses '((:status "accepted" :value 42))))
   (funcall callback "original" nil)
   (should (equal (car responses) '(:status "reply" :text "original")))
   (setq responses nil)
   (slopchat-cli--request nil nil "{\"action\":\"send\",\"text\":\"legacy\"}")
   (should-not responses)
   (funcall callback nil 'steered)
   (should (equal responses '((:status "steered")))))))

(ert-deftest slopchat-acceptance-before-pump ()
 (let ((chat (slopchat--chat-create :count 0 :queued-input (slopchat-queue-create))) events)
  (cl-letf (((symbol-function 'slopchat-log) (lambda (&rest _) (push 'durable events)))
            ((symbol-function 'slopchat-pump) (lambda (_) (should (equal events '(accepted durable))) (push 'pump events))))
   (slopchat-submit chat "input" nil (lambda (_) (push 'accepted events)))
   (should (equal events '(pump accepted durable))))))

(ert-deftest slopchat-cli-ack-before-blocked-pump ()
 (let ((chat (slopchat--chat-create :count 0 :queued-input (slopchat-queue-create))) responses)
  (cl-letf (((symbol-function 'slopchat-log) (lambda (&rest _) nil))
            ((symbol-function 'slopchat-cli--reply) (lambda (_ value) (push value responses)))
            ((symbol-function 'slopchat-pump) (lambda (_)
               (should (equal responses '((:status "accepted" :value 0))))
               (throw 'blocked-pump 'blocked))))
   (should (eq (catch 'blocked-pump
      (slopchat-cli--request chat nil "{\"action\":\"send\",\"text\":\"hello\",\"ack\":true}")) 'blocked))
   (should (equal responses '((:status "accepted" :value 0)))))))

(ert-deftest slopchat-queue-only-never-steers ()
 (let* ((run (slopchat--run-create :turn "live")) (chat (slopchat--chat-create :count 0 :run run :queued-input (slopchat-queue-create))) accepted)
  (cl-letf (((symbol-function 'slopchat-log) (lambda (&rest _) nil))
            ((symbol-function 'slopchat-pump) (lambda (_) nil))
            ((symbol-function 'slopchat-codex-steer) (lambda (&rest _) (ert-fail "must not steer"))))
   (slopchat-submit chat "later" nil (lambda (_) (setq accepted t)) t)
   (should accepted)
   (let ((input (slopchat-dequeue (slopchat-chat-queued-input chat))))
    (should (equal (slopchat-input-text input) "later"))
    (should-not (slopchat-input-steer input))))))

(ert-deftest slopchat-cancel-round-unwinds-and-preserves-queue ()
  (let* ((chat (slopchat--chat-create :queued-input (slopchat-queue-create)))
         (input (slopchat--input-create :text "active"))
         (queued (slopchat--input-create :text "later"))
         interrupted)
    (slopchat-enqueue (slopchat-chat-queued-input chat) queued)
    (cl-letf (((symbol-function 'slopchat--start-input-body)
               (lambda (c _input)
                 (setf (slopchat-chat-run c)
                       (slopchat--run-create :thread "thread" :turn "turn"))
                 (should (slopchat-cancel-round c))
                 (slopchat--check-cancel)
                 (ert-fail "continued cancelled round")))
              ((symbol-function 'slopchat-codex-rpc)
               (lambda (_ method params) (setq interrupted (list method params))))
              ((symbol-function 'slopchat-codex--finish)
               (lambda (run) (setf (slopchat-run-done run) t))))
      (slopchat--start-input chat input))
    (should (equal interrupted '("turn/interrupt" (:threadId "thread" :turnId "turn"))))
    (should-not (slopchat-chat-run chat))
    (should-not (gethash chat slopchat--rounds))
    (should (eq queued (car (slopchat-queue-head (slopchat-chat-queued-input chat)))))
    (should-not (slopchat-cancel-round chat))))
