;;; slopchat-ui-test.el --- Read-only UI tests -*- lexical-binding: t -*-
(require 'slopchat-cli)
(ert-deftest slopchat-ui-startup-loaded ()
 (should (featurep 'slopchat-ui))
 (should (advice-member-p #'slopchat-ui--request 'slopchat-cli--request)))
(ert-deftest slopchat-ui-bounds-and-invalid-input ()
 (slopchat-with-chat
  (dotimes (i 105) (slopchat-log chat "note" (format "m%d" i)))
  (should (= (length (plist-get (slopchat-ui-history chat '(:limit 999)) :messages)) 100))
  (should (= (length (plist-get (slopchat-ui-history chat '(:limit 0)) :messages)) 1))
  (let ((status (slopchat-ui-status chat '(:limit 999))))
   (should (<= (length (plist-get status :nodes)) 100))
   (should (= (plist-get status :viewTotal) (length (slopchat-chat-view chat))))
   (should (= (plist-get status :contextBytes) (slopchat-view-size chat (slopchat-chat-view chat)))))
  (should (= (length (plist-get (slopchat-ui-status chat '(:offset 999)) :nodes)) 0))
  (dolist (p '((:limit -1) (:limit "x") (:before -1) (:after "x")))
   (should-error (slopchat-ui-history chat p)))
  (dolist (p '((:offset -1) (:offset "x") (:limit -1)))
   (should-error (slopchat-ui-status chat p)))))
(ert-deftest slopchat-ui-watermark-tail-and-no-writes ()
 (slopchat-with-chat
  (dotimes (i 6) (slopchat-log chat "note" (format "m%d" i)))
  (let ((watermark (plist-get (slopchat-ui-history chat '(:limit 2)) :count)))
   (slopchat-log chat "note" "tail")
   (let* ((files (directory-files-recursively directory "\\.\\(jsonl\\|json\\)$"))
          (before (mapcar (lambda (f) (cons f (slopchat-test-text f))) files))
          (page (slopchat-ui-history chat (list :before watermark :limit 2)))
          (tail (slopchat-ui-history chat (list :after watermark :limit 2))))
    (should (= (plist-get page :start) 4))
    (should (= (plist-get page :end) 6))
    (should (= (plist-get tail :start) 6))
    (should (= (plist-get tail :end) 7))
    (should (equal (plist-get (aref (plist-get tail :messages) 0) :text) "tail"))
    (should (= (length (plist-get (slopchat-ui-history chat '(:after 99)) :messages)) 0))
    (slopchat-ui-status chat nil)
    (should (equal files (directory-files-recursively directory "\\.\\(jsonl\\|json\\)$")))
    (should (equal before (mapcar (lambda (f) (cons f (slopchat-test-text f))) files)))))))

(ert-deftest slopchat-ui-model-selection ()
 (let ((slopchat-turn-model nil) (calls 0))
  (cl-letf (((symbol-function 'slopchat--connection) (lambda (_) 'fake))
            ((symbol-function 'slopchat-codex-rpc)
             (lambda (_ method params)
              (should (equal method "model/list"))
              (cl-incf calls)
              (if (plist-get params :cursor)
                  '(:data [(:model "second" :displayName "Second")])
                '(:data [(:model "first" :displayName "First")] :nextCursor "page2")))))
   (should (= (length (plist-get (slopchat-ui-models nil) :models)) 2))
   (should (= calls 2))
   (slopchat-ui-select-model nil "second")
   (should (equal slopchat-turn-model "second"))
   (should-error (slopchat-ui-select-model nil "unknown"))
   (should (equal slopchat-turn-model "second"))
   (should-error (slopchat-ui-select-model nil 42))
   (slopchat-ui-select-model nil nil)
   (should-not slopchat-turn-model))))

(ert-deftest slopchat-ui-model-json-null ()
 (let ((calls 0))
  (cl-letf (((symbol-function 'slopchat--connection) (lambda (_) 'fake))
            ((symbol-function 'slopchat-codex-rpc)
             (lambda (&rest _) (cl-incf calls)
              (json-parse-string "{\"data\":[{\"model\":\"first\"}],\"nextCursor\":null}" :object-type 'plist :false-object :false))))
   (should (= (length (plist-get (slopchat-ui-models nil) :models)) 1))
   (should (= calls 1)))))

(ert-deftest slopchat-ui-model-wire-default ()
 (let ((slopchat-turn-model nil))
  (cl-letf (((symbol-function 'slopchat--connection) (lambda (_) 'fake))
            ((symbol-function 'slopchat-codex-rpc) (lambda (&rest _) '(:data [] :nextCursor :null))))
   (should (equal (json-serialize (slopchat-ui-models nil)) "{\"selected\":null,\"models\":[]}"))
   (should (eq (plist-get (slopchat-ui-select-model nil :null) :selected) :null))
   (should-not slopchat-turn-model))))

(ert-deftest slopchat-cli-disconnected-clients-released ()
  (let* ((client (make-pipe-process :name "slopchat-test-client" :noquery t))
         (other (make-pipe-process :name "slopchat-test-other" :noquery t))
         (slopchat--clients (list client other)))
    (unwind-protect
        (progn
          (process-put client 'pending "partial request")
          (slopchat-cli--client-sentinel client "open")
          (should (= (length slopchat--clients) 2))
          (delete-process client)
          (slopchat-cli--client-sentinel client "closed")
          (should (equal slopchat--clients (list other)))
          (should-not (process-get client 'pending)))
      (dolist (p (list client other))
        (when (process-live-p p) (delete-process p))))))

(ert-deftest slopchat-stream-transient-bounded-and-cancelled ()
 (slopchat-with-chat
  (let ((token (list nil)))
   (puthash chat token slopchat--rounds)
   (unwind-protect
    (progn
     (slopchat--stream-event chat token "item/agentMessage/delta" '(:delta "Hello "))
     (slopchat--stream-event chat token "item/agentMessage/delta" '(:delta "world"))
     (should (equal (plist-get (slopchat-chat-stream chat) :text) "Hello world"))
     (should (= (slopchat-chat-count chat) 0))
     (should (equal (plist-get (slopchat-ui-status chat nil) :stream) (slopchat-chat-stream chat)))
     (slopchat--stream-event chat token "item/agentMessage/delta" (list :delta (make-string 20000 ?x)))
     (should (= (length (plist-get (slopchat-chat-stream chat) :text)) 16000))
     (slopchat-cancel-round chat)
     (should (equal (plist-get (slopchat-chat-stream chat) :state) "cancelled"))
     (slopchat--stream-event chat token "item/agentMessage/delta" '(:delta "late"))
     (should (= (length (plist-get (slopchat-chat-stream chat) :text)) 16000)))
    (remhash chat slopchat--rounds)))))
