;;; slopchat-ui-test.el --- Read-only UI tests -*- lexical-binding: t -*-
(require 'slopchat-cli)
(ert-deftest slopchat-ui-startup-loaded ()
 (should (featurep 'slopchat-ui))
 (should (advice-member-p #'slopchat-ui--request 'slopchat-cli--request)))
(ert-deftest slopchat-ui-bounds-and-invalid-input ()
 (slopchat-with-chat
  (dotimes (i 105) (slopchat-log chat "note" (format "m%d" i)))
  (should (= (length (plist-get (slopchat-ui-history chat '(:limit 999)) :messages)) 100))
  (should (= (length (plist-get (slopchat-ui-history chat '(:limit 0)) :messages)) 1))
  (let ((status (slopchat-ui-status chat '(:limit 999))))
   (should (<= (length (plist-get status :nodes)) 100))
   (should (= (plist-get status :viewTotal) (length (slopchat-chat-view chat))))
   (should (= (plist-get status :contextBytes) (slopchat-view-size chat (slopchat-chat-view chat)))))
  (should (= (length (plist-get (slopchat-ui-status chat '(:offset 999)) :nodes)) 0))
  (dolist (p '((:limit -1) (:limit "x") (:before -1) (:after "x")))
   (should-error (slopchat-ui-history chat p)))
  (dolist (p '((:offset -1) (:offset "x") (:limit -1)))
   (should-error (slopchat-ui-status chat p)))))
(ert-deftest slopchat-ui-watermark-tail-and-no-writes ()
 (slopchat-with-chat
  (dotimes (i 6) (slopchat-log chat "note" (format "m%d" i)))
  (let ((watermark (plist-get (slopchat-ui-history chat '(:limit 2)) :count)))
   (slopchat-log chat "note" "tail")
   (let* ((files (directory-files-recursively directory "\\.\\(jsonl\\|json\\)$"))
          (before (mapcar (lambda (f) (cons f (slopchat-test-text f))) files))
          (page (slopchat-ui-history chat (list :before watermark :limit 2)))
          (tail (slopchat-ui-history chat (list :after watermark :limit 2))))
    (should (= (plist-get page :start) 4))
    (should (= (plist-get page :end) 6))
    (should (= (plist-get tail :start) 6))
    (should (= (plist-get tail :end) 7))
    (should (equal (plist-get (aref (plist-get tail :messages) 0) :text) "tail"))
    (should (= (length (plist-get (slopchat-ui-history chat '(:after 99)) :messages)) 0))
    (slopchat-ui-status chat nil)
    (should (equal files (directory-files-recursively directory "\\.\\(jsonl\\|json\\)$")))
    (should (equal before (mapcar (lambda (f) (cons f (slopchat-test-text f))) files)))))))


(ert-deftest slopchat-cli-disconnected-clients-released ()
  (let* ((client (make-pipe-process :name "slopchat-test-client" :noquery t))
         (other (make-pipe-process :name "slopchat-test-other" :noquery t))
         (slopchat--clients (list client other)))
    (unwind-protect
        (progn
          (process-put client 'pending "partial request")
          (slopchat-cli--client-sentinel client "open")
          (should (= (length slopchat--clients) 2))
          (delete-process client)
          (slopchat-cli--client-sentinel client "closed")
          (should (equal slopchat--clients (list other)))
          (should-not (process-get client 'pending)))
      (dolist (p (list client other))
        (when (process-live-p p) (delete-process p))))))
