;;; -*- lexical-binding: t -*-
(require 'ert)
(require 'cl-lib)
(require 'slopchat-cli)
(ert-deftest slopchat-opt-in-acceptance ()
 (let (responses callback)
  (cl-letf (((symbol-function 'slopchat-cli--reply) (lambda (_ value) (push value responses)))
            ((symbol-function 'slopchat-submit) (lambda (_ _text cb &optional accepted) (setq callback cb) (when accepted (funcall accepted 42)) 42)))
   (slopchat-cli--request nil nil "{\"action\":\"send\",\"text\":\"hello\",\"ack\":true}")
   (should (equal responses '((:status "accepted" :value 42))))
   (funcall callback "original" nil)
   (should (equal (car responses) '(:status "reply" :text "original")))
   (setq responses nil)
   (slopchat-cli--request nil nil "{\"action\":\"send\",\"text\":\"legacy\"}")
   (should-not responses)
   (funcall callback nil 'steered)
   (should (equal responses '((:status "steered")))))))

(ert-deftest slopchat-acceptance-before-pump ()
 (let ((chat (slopchat--chat-create :count 0 :queued-input (slopchat-queue-create))) events)
  (cl-letf (((symbol-function 'slopchat-log) (lambda (&rest _) (push 'durable events)))
            ((symbol-function 'slopchat-pump) (lambda (_) (should (equal events '(accepted durable))) (push 'pump events))))
   (slopchat-submit chat "input" nil (lambda (_) (push 'accepted events)))
   (should (equal events '(pump accepted durable))))))

(ert-deftest slopchat-cli-ack-before-blocked-pump ()
 (let ((chat (slopchat--chat-create :count 0 :queued-input (slopchat-queue-create))) responses)
  (cl-letf (((symbol-function 'slopchat-log) (lambda (&rest _) nil))
            ((symbol-function 'slopchat-cli--reply) (lambda (_ value) (push value responses)))
            ((symbol-function 'slopchat-pump) (lambda (_)
               (should (equal responses '((:status "accepted" :value 0))))
               (throw 'blocked-pump 'blocked))))
   (should (eq (catch 'blocked-pump
      (slopchat-cli--request chat nil "{\"action\":\"send\",\"text\":\"hello\",\"ack\":true}")) 'blocked))
   (should (equal responses '((:status "accepted" :value 0)))))))
