;;; slopchat-store.el --- Durable log and summary tree -*- lexical-binding: t -*-
(require 'cl-lib)
(require 'json)
(require 'subr-x)

(defvar slopchat-message-bytes 30000)
(defvar slopchat-view-high 128000)
(defvar slopchat-view-low 64000)
(defvar slopchat-compaction-high 32000)
(defvar slopchat-compaction-low 16000)
(defvar slopchat-page-bytes 4000)

(cl-defstruct (slopchat-queue (:constructor slopchat-queue-create)) head tail)
(defun slopchat-enqueue (queue value)
  (let ((cell (list value)))
    (if (slopchat-queue-tail queue)
        (setcdr (slopchat-queue-tail queue) cell)
      (setf (slopchat-queue-head queue) cell))
    (setf (slopchat-queue-tail queue) cell)))
(defun slopchat-queue-front (queue value)
  (let ((cell (cons value (slopchat-queue-head queue))))
    (setf (slopchat-queue-head queue) cell)
    (unless (slopchat-queue-tail queue) (setf (slopchat-queue-tail queue) cell))))
(defun slopchat-dequeue (queue)
  (prog1 (pop (slopchat-queue-head queue))
    (unless (slopchat-queue-head queue) (setf (slopchat-queue-tail queue) nil))))

(cl-defstruct (slopchat-chat (:constructor slopchat--chat-create))
  directory lock (count 0) messages nodes (cursor 0) view comp-view
  batching comp-batching jobs leaves (leaf-slots 0) states failed (active 0) transport run queued-input
  agent closed)

(defun slopchat-bytes (text) (length (encode-coding-string text 'utf-8-unix)))
(defun slopchat-split (text limit)
  "Split TEXT without losing characters, at most LIMIT UTF-8 bytes per part."
  (when (< limit 4) (error "UTF-8 chunk limit must be at least four"))
  (let ((start 0) (size 0) pieces)
    (dotimes (i (length text))
      (let ((width (slopchat-bytes (substring text i (1+ i)))))
        (when (> (+ size width) limit)
          (push (substring text start i) pieces) (setq start i size 0))
        (cl-incf size width)))
    (push (substring text start) pieces)
    (nreverse pieces)))
(defun slopchat-clip (text)
  (if (<= (length text) 30000) text
    (concat (substring text 0 15000) (substring text -15000))))

(defun slopchat--json-read (text)
  (json-parse-string text :object-type 'plist :array-type 'list
                     :null-object nil :false-object nil))
(defun slopchat--write (file text &optional append)
  (let ((coding-system-for-write 'utf-8-unix)
        (write-region-inhibit-fsync nil))
    (with-temp-buffer
      (insert text) (write-region (point-min) (point-max) file append 'silent))))
(defun slopchat--atomic (file value)
  (let ((temp (make-temp-file (concat file ".tmp-"))))
    (unwind-protect
        (progn (slopchat--write temp (concat (json-serialize value) "\n"))
               (rename-file temp file t))
      (when (file-exists-p temp) (delete-file temp)))))
(defun slopchat--recover-record-tail (file)
  "Discard only an incomplete last record, preserving its bytes in a side file."
  (with-temp-buffer
    (set-buffer-multibyte nil) (insert-file-contents-literally file)
    (unless (or (= (buffer-size) 0) (eq (char-before (point-max)) ?\n))
      (goto-char (point-max))
      (let* ((end (if (search-backward "\n" nil t) (1+ (point)) (point-min)))
             (size (1- end)) (tail (buffer-substring end (point-max)))
             (backup (make-temp-file (concat file ".incomplete-"))))
        (let ((coding-system-for-write 'no-conversion) (write-region-inhibit-fsync nil))
          (write-region tail nil backup nil 'silent))
        (unless (and (executable-find "truncate")
                     (= (call-process "truncate" nil nil nil "--size" (number-to-string size) file) 0))
          (error "Cannot recover incomplete tail in %s; copied to %s" file backup))
        (message "SlopChat recovered incomplete record in %s; partial bytes saved in %s" file backup)))))
(defun slopchat--records (directory consume)
  (dolist (file (sort (directory-files directory t "\\.jsonl\\'") #'string<))
    (slopchat--recover-record-tail file)
    (with-temp-buffer
      (let ((coding-system-for-read 'utf-8-unix)) (insert-file-contents file))
      (unless (or (= (point-min) (point-max)) (eq (char-before (point-max)) ?\n))
        (error "Incomplete final log record in %s; existing complete records are preserved" file))
      (goto-char (point-min))
      (while (< (point) (point-max))
        (let ((line (buffer-substring-no-properties (point) (line-end-position))))
          (condition-case err (funcall consume (slopchat--json-read line))
            (error (error "Invalid log record in %s line %s: %s"
                          file (line-number-at-pos) (error-message-string err)))))
        (forward-line 1)))))
(defun slopchat--lock (chat)
  "Hold a kernel flock through a pipe-owned helper; crashes release it."
  (unless (executable-find "flock") (error "Chat locking requires flock"))
  (let* ((buffer (generate-new-buffer " *slopchat-lock*"))
         (lock (make-process
                :name "slopchat-lock" :buffer buffer :connection-type 'pipe
                :command (list "flock" "--close" "--nonblock" "--conflict-exit-code" "75"
                               (expand-file-name ".lock" (slopchat-chat-directory chat))
                               "sh" "-c" "printf 'locked\\n'; cat >/dev/null")
                :noquery t))
         (deadline (+ (float-time) 5)))
    (setf (slopchat-chat-lock chat) lock)
    (while (and (process-live-p lock)
                (with-current-buffer buffer (= (buffer-size) 0))
                (< (float-time) deadline))
      (accept-process-output lock 0.05))
    (unless (and (process-live-p lock)
                 (with-current-buffer buffer (string-prefix-p "locked\n" (buffer-string))))
      (delete-process lock) (kill-buffer buffer)
      (error "Chat is locked or flock failed: %s" (slopchat-chat-directory chat)))))

(defun slopchat-key (level index) (list level index))
(defun slopchat-node (chat key) (gethash key (slopchat-chat-nodes chat)))
(defun slopchat-range (key)
  (let ((span (ash 1 (car key)))) (cons (* span (cadr key)) span)))
(defun slopchat--line (chat key)
  (let* ((node (slopchat-node chat key)) (range (slopchat-range key)))
    (unless node (error "Unbuilt node: %S" key))
    (format "%d+%d|%s\n" (car range) (cdr range)
            (replace-regexp-in-string "[\r\n]+" " " (plist-get node :text)))))
(cl-defun slopchat-render (chat &optional (view nil supplied))
  (concat "<chat>\n" (mapconcat (lambda (key) (slopchat--line chat key))
                              (if supplied view (slopchat-chat-view chat)) "") "</chat>"))
(defun slopchat-view-size (chat view)
  (+ (slopchat-bytes "<chat>\n</chat>")
     (cl-loop for key in view sum (slopchat-bytes (slopchat--line chat key)))))

(defun slopchat-best-merge (view total &optional available)
  "Return the cell whose first two sibling entries are most due.
Compare integer cross-products; TOTAL is the number of logged messages."
  (let ((cell view) best best-age best-span best-first)
    (while (cdr cell)
      (let* ((a (car cell)) (b (cadr cell)) (level (car a))
             (index (cadr a)) (span (ash 1 level))
             (parent (list (1+ level) (/ index 2))))
        (when (and (= level (car b)) (= (cadr b) (1+ index))
                   (= (% index 2) 0) (or (null available) (funcall available parent)))
          (let* ((first (* index span)) (age (- total (+ first (* 2 span) -1))))
            (when (or (null best)
                      (> (* age best-span) (* best-age span))
                      (and (= (* age best-span) (* best-age span)) (< first best-first)))
              (setq best cell best-age age best-span span best-first first)))))
      (setq cell (cdr cell)))
    best))
(defun slopchat-merge-to (chat view low &optional line-budget)
  "Merge VIEW in place until LOW bytes (or test LINE-BUDGET), if possible."
  (let ((size (slopchat-view-size chat view)) candidate)
    (while (and (if line-budget (> (length view) line-budget) (> size low))
                (setq candidate
                      (slopchat-best-merge
                       view (slopchat-chat-count chat)
                       (lambda (parent) (slopchat-node chat parent)))))
      (let* ((a (car candidate)) (b (cadr candidate))
             (parent (list (1+ (car a)) (/ (cadr a) 2))))
        (cl-incf size (- (slopchat-bytes (slopchat--line chat parent))
                        (slopchat-bytes (slopchat--line chat a))
                        (slopchat-bytes (slopchat--line chat b))))
        (setcar candidate parent) (setcdr candidate (cddr candidate))))
    view))
(defun slopchat--shrink (chat)
  (when (> (slopchat-view-size chat (slopchat-chat-view chat)) slopchat-view-high)
    (setf (slopchat-chat-batching chat) t))
  (when (slopchat-chat-batching chat)
    (setf (slopchat-chat-view chat)
          (slopchat-merge-to chat (slopchat-chat-view chat) slopchat-view-low))
    (setf (slopchat-chat-comp-batching chat) t)
    (when (<= (slopchat-view-size chat (slopchat-chat-view chat)) slopchat-view-low)
      (setf (slopchat-chat-batching chat) nil)))
  (when (> (slopchat-view-size chat (slopchat-chat-comp-view chat)) slopchat-compaction-high)
    (setf (slopchat-chat-comp-batching chat) t))
  (when (slopchat-chat-comp-batching chat)
    (setf (slopchat-chat-comp-view chat)
          (slopchat-merge-to chat (slopchat-chat-comp-view chat) slopchat-compaction-low))
    (when (<= (slopchat-view-size chat (slopchat-chat-comp-view chat)) slopchat-compaction-low)
      (setf (slopchat-chat-comp-batching chat) nil))))
(defun slopchat-checkpoint (chat)
  "Atomically persist view and its contiguous-log cursor in one file."
  (slopchat--atomic
   (expand-file-name "view.json" (slopchat-chat-directory chat))
   `(:version 1 :cursor ,(slopchat-chat-cursor chat)
     :view ,(vconcat (mapcar #'vconcat (slopchat-chat-view chat)))
     :compactionView ,(vconcat (mapcar #'vconcat (slopchat-chat-comp-view chat)))
     :batching ,(if (slopchat-chat-batching chat) t :false)
     :compactionBatching ,(if (slopchat-chat-comp-batching chat) t :false))))
(defun slopchat--publish (chat)
  (while (slopchat-node chat (list 0 (slopchat-chat-cursor chat)))
    (let ((key (list 0 (slopchat-chat-cursor chat))))
      (setf (slopchat-chat-view chat) (nconc (slopchat-chat-view chat) (list key))
            (slopchat-chat-comp-view chat) (nconc (slopchat-chat-comp-view chat) (list key)))
      (cl-incf (slopchat-chat-cursor chat))))
  (slopchat--shrink chat)
  (slopchat-checkpoint chat))
(defun slopchat--admit-leaves (chat)
  ;; At most eight unbuilt admitted leaves. Later leaves wait in an O(1) FIFO,
  ;; so scheduling does not scan earlier tree nodes or a growing log.
  (while (and (< (slopchat-chat-leaf-slots chat) 8)
              (slopchat-queue-head (slopchat-chat-leaves chat)))
    (let ((key (slopchat-dequeue (slopchat-chat-leaves chat))))
      (cl-incf (slopchat-chat-leaf-slots chat))
      (puthash key 'queued (slopchat-chat-states chat))
      (slopchat-enqueue (slopchat-chat-jobs chat) key))))
(defun slopchat--queue-node (chat key)
  (unless (or (slopchat-node chat key) (gethash key (slopchat-chat-states chat)))
    (if (= (car key) 0)
        (progn (puthash key 'waiting (slopchat-chat-states chat))
               (slopchat-enqueue (slopchat-chat-leaves chat) key)
               (slopchat--admit-leaves chat))
      (puthash key 'queued (slopchat-chat-states chat))
      (slopchat-enqueue (slopchat-chat-jobs chat) key))))

(defun slopchat-source (chat key)
  (if (= (car key) 0)
      (let ((message (gethash (cadr key) (slopchat-chat-messages chat))))
        (format "%s: %s" (plist-get message :kind) (plist-get message :text)))
    (let* ((level (1- (car key))) (index (* 2 (cadr key)))
           (a (slopchat-node chat (list level index)))
           (b (slopchat-node chat (list level (1+ index)))))
      (when (and a b) (concat (plist-get a :text) "\n" (plist-get b :text))))))
(defun slopchat--offer (chat key)
  (let ((source (slopchat-source chat key)))
    (when source
      (if (<= (slopchat-bytes source) 512) (slopchat-build chat key source)
        (slopchat--queue-node chat key)))))
(defun slopchat-build (chat key text)
  "Commit an immutable node, then offer its newly ready parent."
  (unless (slopchat-node chat key)
    (let* ((node `(:l ,(car key) :i ,(cadr key) :text ,text :size ,(slopchat-bytes text)))
           (file (expand-file-name (concat "tree/" (format-time-string "%Y-%m-%d") ".jsonl")
                                   (slopchat-chat-directory chat))))
      (slopchat--write file (concat (json-serialize node) "\n") t)
      (puthash key node (slopchat-chat-nodes chat))
      (when (and (= (car key) 0) (memq (gethash key (slopchat-chat-states chat)) '(queued active failed)))
        (cl-decf (slopchat-chat-leaf-slots chat)))
      (puthash key 'built (slopchat-chat-states chat))
      (slopchat--admit-leaves chat)
      (slopchat--offer chat (list (1+ (car key)) (/ (cadr key) 2)))
      (slopchat--publish chat)))
  (slopchat-node chat key))
(defun slopchat-log (chat kind text)
  "Append TEXT losslessly (except clipped echo), returning its message IDs."
  (when (slopchat-chat-closed chat) (error "Chat is closed"))
  (unless (member kind '("user" "slopchat" "unii" "tool" "echo" "work" "note"))
    (error "Unknown message kind: %s" kind))
  (let ((parts (if (equal kind "echo") (list (slopchat-clip text))
                 (slopchat-split text slopchat-message-bytes))) ids)
    (dolist (part parts)
      (let* ((id (slopchat-chat-count chat))
             (date (format-time-string "%Y-%m-%dT%H:%M:%S.%3NZ" nil t))
             (message `(:i ,id :kind ,kind :text ,part :size ,(slopchat-bytes part) :date ,date))
             (file (expand-file-name (concat "main/" (substring date 0 10) ".jsonl")
                                     (slopchat-chat-directory chat))))
        (slopchat--write file (concat (json-serialize message) "\n") t)
        (puthash id message (slopchat-chat-messages chat))
        (cl-incf (slopchat-chat-count chat)) (push id ids)
        (dolist (key (slopchat-chat-failed chat))
          (puthash key 'queued (slopchat-chat-states chat))
          (slopchat-enqueue (slopchat-chat-jobs chat) key))
        (setf (slopchat-chat-failed chat) nil)
        (slopchat--offer chat (list 0 id))))
    (nreverse ids)))
(defun slopchat--validate-view (chat view cursor)
  (let ((next 0))
    (dolist (key view)
      (unless (and (= (length key) 2) (natnump (car key)) (natnump (cadr key))
                   (slopchat-node chat key)) (error "Invalid persisted view node: %S" key))
      (let ((range (slopchat-range key)))
        (unless (= next (car range)) (error "Noncontiguous persisted view"))
        (cl-incf next (cdr range))))
    (unless (= next cursor) (error "Persisted view cursor mismatch"))))
(defun slopchat-open (directory)
  "Open DIRECTORY exclusively; preserve its checkpoint and recover only its tail."
  (let* ((directory (file-name-as-directory (expand-file-name directory)))
         (chat (slopchat--chat-create
                :directory directory :messages (make-hash-table :test 'eql)
                :nodes (make-hash-table :test 'equal) :states (make-hash-table :test 'equal)
                :jobs (slopchat-queue-create) :leaves (slopchat-queue-create) :queued-input (slopchat-queue-create))))
    (make-directory directory t)
    (condition-case err
        (progn
          (slopchat--lock chat)
          (make-directory (expand-file-name "main" directory) t)
          (make-directory (expand-file-name "tree" directory) t)
          (slopchat--records
           (expand-file-name "main" directory)
           (lambda (message)
             (unless (and (= (plist-get message :i) (slopchat-chat-count chat))
                          (stringp (plist-get message :text))
                          (= (plist-get message :size) (slopchat-bytes (plist-get message :text)))
                          (member (plist-get message :kind) '("user" "slopchat" "unii" "tool" "echo" "work" "note"))
                          (stringp (plist-get message :date))) (error "Invalid message"))
             (puthash (plist-get message :i) message (slopchat-chat-messages chat))
             (cl-incf (slopchat-chat-count chat))))
          (slopchat--records
           (expand-file-name "tree" directory)
           (lambda (node)
             (let* ((key (list (plist-get node :l) (plist-get node :i)))
                    (range (and (natnump (car key)) (natnump (cadr key)) (slopchat-range key))))
               (unless (and range (<= (+ (car range) (cdr range)) (slopchat-chat-count chat))
                            (stringp (plist-get node :text))
                            (= (plist-get node :size) (slopchat-bytes (plist-get node :text)))
                            (not (slopchat-node chat key))) (error "Invalid or duplicate node"))
               (puthash key node (slopchat-chat-nodes chat))
               (puthash key 'built (slopchat-chat-states chat)))))
          (let ((file (expand-file-name "view.json" directory)))
            (if (file-exists-p file)
                (let ((checkpoint (with-temp-buffer (insert-file-contents file)
                                                   (slopchat--json-read (buffer-string)))))
                  (unless (= (plist-get checkpoint :version) 1) (error "Unsupported checkpoint"))
                  (setf (slopchat-chat-cursor chat) (plist-get checkpoint :cursor)
                        (slopchat-chat-view chat) (plist-get checkpoint :view)
                        (slopchat-chat-comp-view chat) (plist-get checkpoint :compactionView)
                        (slopchat-chat-batching chat) (plist-get checkpoint :batching)
                        (slopchat-chat-comp-batching chat) (plist-get checkpoint :compactionBatching))
                  (unless (<= (slopchat-chat-cursor chat) (slopchat-chat-count chat))
                    (error "Checkpoint ahead of log"))
                  (slopchat--validate-view chat (slopchat-chat-view chat) (slopchat-chat-cursor chat))
                  (slopchat--validate-view chat (slopchat-chat-comp-view chat) (slopchat-chat-cursor chat)))
              (when (> (slopchat-chat-count chat) 0)
                (error "Existing log has no view checkpoint; refusing to rebuild its view"))
              (slopchat-checkpoint chat)))
          ;; Rebuild work queues once on startup, not on every message. Older view
          ;; entries are retained; only committed leaves beyond cursor are published.
          (dotimes (i (slopchat-chat-count chat))
            (unless (slopchat-node chat (list 0 i)) (slopchat--offer chat (list 0 i))))
          (let (parents)
            (maphash (lambda (key _node) (push (list (1+ (car key)) (/ (cadr key) 2)) parents))
                     (slopchat-chat-nodes chat))
            (dolist (key parents) (unless (slopchat-node chat key) (slopchat--offer chat key))))
          (when (< (slopchat-chat-cursor chat) (slopchat-chat-count chat))
            (slopchat--publish chat))
          chat)
      (error (slopchat-close chat) (signal (car err) (cdr err))))))
(defun slopchat-close (chat)
  "Release this instance's kernel lock; completed writes are already durable."
  (let ((lock (slopchat-chat-lock chat)))
    (when (processp lock)
      (when (process-live-p lock)
        (process-send-eof lock)
        (let ((deadline (+ (float-time) 2)))
          (while (and (process-live-p lock) (< (float-time) deadline))
            (accept-process-output lock 0.05)))
        (when (process-live-p lock) (delete-process lock)))
      (when (buffer-live-p (process-buffer lock)) (kill-buffer (process-buffer lock)))))
  (setf (slopchat-chat-closed chat) t))

(defun slopchat-zoom (chat id span &optional page)
  (unless (and (natnump id) (integerp span) (> span 0) (= (logand span (1- span)) 0)
               (= (% id span) 0) (<= (+ id span) (slopchat-chat-count chat)))
    (error "Invalid zoom range: %S+%S" id span))
  (if (= span 1)
      (let* ((message (gethash id (slopchat-chat-messages chat)))
             (parts (slopchat-split (plist-get message :text) slopchat-page-bytes))
             (page (or page 0)))
        (unless (and (natnump page) (< page (length parts))) (error "Invalid message page"))
        `(:id ,id :kind ,(plist-get message :kind) :text ,(nth page parts)
              :page ,page :pages ,(length parts) :date ,(plist-get message :date)))
    (let* ((level (let ((n span) (l -1)) (while (> n 1) (setq n (/ n 2) l (1+ l))) l))
           (index (/ id (/ span 2)))
           (a (slopchat-node chat (list level index)))
           (b (slopchat-node chat (list level (1+ index)))))
      (unless (and a b) (error "Zoom children are not built"))
      (vector a b))))
(defun slopchat-date (chat id)
  (let ((message (and (natnump id) (gethash id (slopchat-chat-messages chat)))))
    (unless message (error "Unknown message ID: %S" id))
    (plist-get message :date)))

(provide 'slopchat-store)
;;; slopchat-store.el ends here
