;;; slopchat-process.el --- Bounded command sessions -*- lexical-binding: t -*-
(require 'cl-lib)
(defvar slopchat-process--sessions (make-hash-table :test 'equal))
(defvar slopchat-process-output-limit 65536)
(defun slopchat-process--wait (process milliseconds)
  (unless (and (integerp milliseconds) (<= 0 milliseconds 10000)) (error "yield-time-ms must be between 0 and 10000"))
  (let ((deadline (+ (float-time) (/ milliseconds 1000.0))))
    (while (and (process-live-p process) (< (float-time) deadline))
      (accept-process-output process (min 0.05 (max 0 (- deadline (float-time)))))))
  (accept-process-output process 0))
(defun slopchat-process--result (id milliseconds)
  (let ((process (gethash id slopchat-process--sessions)))
    (unless process (error "Unknown process session: %s" id))
    (slopchat-process--wait process milliseconds)
    (let ((output (or (process-get process 'output) "")) (dropped (or (process-get process 'dropped) 0)) (live (process-live-p process)))
      (process-put process 'output "") (process-put process 'dropped 0)
      (prog1 (list :session-id id :status (if live "running" "exited") :output output :dropped-chars dropped :exit-code (unless live (process-exit-status process)))
        (unless live (remhash id slopchat-process--sessions))))))
(defun slopchat-exec-command (command &optional workdir yield-time-ms)
  "Run COMMAND; return bounded output and a session ID for further waits."
  (unless (stringp command) (error "command must be a string"))
  (setq yield-time-ms (or yield-time-ms 1000))
  (unless (and (integerp yield-time-ms) (<= 0 yield-time-ms 10000)) (error "Invalid yield-time-ms"))
  (when (>= (hash-table-count slopchat-process--sessions) 16) (error "Process session limit reached; collect or cancel existing sessions"))
  (let* ((default-directory (file-name-as-directory (expand-file-name (or workdir default-directory))))
         (id (symbol-name (gensym "process-")))
         (process (make-process :name id :command (list "bash" "-c" command) :connection-type 'pipe :coding 'utf-8-unix :noquery t :buffer nil
           :filter (lambda (p chunk)
                     (let* ((text (concat (or (process-get p 'output) "") chunk)) (excess (max 0 (- (length text) slopchat-process-output-limit))))
                       (process-put p 'dropped (+ (or (process-get p 'dropped) 0) excess))
                       (process-put p 'output (substring text excess)))) :sentinel #'ignore)))
    (puthash id process slopchat-process--sessions)
    (slopchat-process--result id yield-time-ms)))
(defun slopchat-write-stdin (session-id &optional chars yield-time-ms)
  "Poll SESSION-ID with empty CHARS, or send input, then wait boundedly."
  (let ((process (gethash session-id slopchat-process--sessions)))
    (unless process (error "Unknown process session: %s" session-id))
    (unless (or (null chars) (stringp chars)) (error "chars must be a string"))
    (when (and chars (not (equal chars ""))) (process-send-string process chars))
    (slopchat-process--result session-id (or yield-time-ms 1000))))
(defun slopchat-cancel-process (session-id)
  "Terminate a command session and collect its remaining output."
  (let ((process (gethash session-id slopchat-process--sessions)))
    (unless process (error "Unknown process session: %s" session-id))
    (when (process-live-p process) (delete-process process))
    (slopchat-process--result session-id 0)))
(provide 'slopchat-process)
